version: '3.8'

services:
  # --- THE BACKEND CONTAINER ---
  backend:
    build: ./backend
    container_name: streamdash_backend
    ports:
      - "8000:8000" # Maps your PC's port 8000 to the container's port 8000
    volumes:
      - ./backend:/app # Hot-Reloading: Syncs your local code to the container in real-time
      - /app/node_modules # Prevents your local node_modules from overwriting the container's
    env_file:
      - ./backend/.env # Loads your Cloudinary and Mongo URIs

  # --- THE FRONTEND CONTAINER ---
  frontend:
    build: ./frontend
    container_name: streamdash_frontend
    ports:
      - "5174:5174" # Maps your PC's port to Vite's port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend # Tells Docker to start the backend before the frontend