version: '3.8'

services:
  # --- BACKEND SERVICE ---
  backend:
    build:
      context: ./backend
      target: dev   # switch to 'prod' for production build
    container_name: streamdash_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app        # hot reload in dev
      - /app/node_modules     # prevent overwriting node_modules
    env_file:
      - ./backend/.env        # environment variables

  # --- FRONTEND SERVICE ---
  frontend:
    build:
      context: ./frontend
      target: dev   # switch to 'prod' for production build
    container_name: streamdash_frontend
    ports:
      - "5174:5174"           # dev mode (Vite)
      # for prod, map "5174:80" since Nginx serves on 80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend # Tells Docker to start the backend before the frontend